FROM oven/bun:1 AS base

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/web/package.json ./apps/web/
COPY packages ./packages

RUN bun install

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["bun", "run", "dev"]


