FROM oven/bun:1.3.3

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/poller/package.json ./apps/poller/package.json
COPY packages ./packages

RUN bun install --frozen-lockfile

COPY apps/poller ./apps/poller

WORKDIR /app/apps/poller

CMD ["bun", "index.ts"]
