FROM oven/bun:1.3.3

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/server/package.json ./apps/server/package.json
COPY packages ./packages

RUN bun install --frozen-lockfile

COPY apps/server ./apps/server

WORKDIR /app/apps/server

EXPOSE 4000

CMD ["bun", "index.ts"]